stages:
  - test

.test:
  stage: test
  script:
    - pipenv install --dev --skip-lock --system
    - pipenv check --system
    - flake8
    - pytest
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
    - /^feature\/.*$/
    - /^fix\/.*$/
    - /^chore\/.*$/

test-2.7:
  extends: .test
  image: 'inspectorio/python:2.7'

test-3.6:
  extends: .test
  image: 'inspectorio/python:3.6'

test-3.7:
  extends: .test
  image: 'inspectorio/python:3.7'
