stages:
  - test

# TODO: simplify configuration using `extends` after migration to GitLab 11.3
# https://docs.gitlab.com/ee/ci/yaml/README.html#extends

.test: &test
  stage: test
  script:
    - pipenv install --dev --skip-lock --system
    - pytest
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - master
    - demo
    - dev
    - /^v\d+\.\d+\.\d+$/
    - /^v\d+\.\d+\.\d+-rc\.\d+$/
    - /^v\d+\.\d+\.\d+-alpha\.\d+$/
    - /^release-v\d+\.\d+\.\d+$/
    - /^feature\/.*$/
    - /^fix\/.*$/
    - /^chore\/.*$/

test-2.7:
  image: "inspectorio/python:2.7"
  <<: *test

test-3.6:
  image: "inspectorio/python:3.6"
  <<: *test

test-3.7:
  image: "inspectorio/python:3.7"
  <<: *test
