dist: xenial
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - 'nightly'

stages:
  - lint
  - test

matrix:
  include:
    - stage: lint
      name: flake8
      python: '3.8'
  allow_failures:
    - python: 'nightly'

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -v
